In [66]:
import matplotlib.pyplot as plt
import numpy as np
import pickle


s_list = [6]
Ry_list = [0.02, 0.25, 0.5]
no_datasets = 1

In [67]:
result = dict()
for i in range(no_datasets):
    for (s, Ry) in zip(s_list, Ry_list):
        with open(f'out_{i}_{s}_{Ry}.pickle', 'rb') as handle:
            result[i, s, Ry] = pickle.load(handle)

In [68]:
for i in range(no_datasets):
    for (s, Ry) in zip(s_list, Ry_list):
        R2_vs, q_vs, z_vs, sigma2_vs, beta_v_tilde = result[i, s, Ry]

        plt.hist(R2_vs)
        plt.title(f"R2_hist_{i}_{s}_{Ry}.png")
        plt.savefig(f'R2_hist_{i}_{s}_{Ry}.png')
        plt.close()

        plt.hist(q_vs)
        plt.title(f"q_hist_{i}_{s}_{Ry}.png")
        plt.savefig(f'q_hist_{i}_{s}_{Ry}.png')
        plt.close()


        plt.hist(sigma2_vs)
        plt.title(f"sigma2_hist_{i}_{s}_{Ry}.png")
        plt.savefig(f'sigma2_hist_{i}_{s}_{Ry}.png')
        plt.close()

In [39]:
import jax.numpy as jnp
import jax
z = [0, 1, 0]
X = [[2, 3, 4], [5, 6, 7], [8, 9, 10]]
X = jnp.array(X)
z = jnp.array(z)
print(reconstruct(X, z))

[[3. 0. 0.]
 [6. 0. 0.]
 [9. 0. 0.]]


In [41]:
reconstruct(X, z).T@reconstruct(X, z)

Array([[126.,   0.,   0.],
       [  0.,   0.,   0.],
       [  0.,   0.,   0.]], dtype=float32)

In [43]:
jnp.where(z == 1, X, z)

Array([[0, 3, 0],
       [0, 6, 0],
       [0, 9, 0]], dtype=int32)

In [52]:
n = 5
jnp.where(jnp.arange(n)<=2,  jnp.ones(n), jnp.zeros(n))

Array([1., 1., 1., 0., 0.], dtype=float32)

In [60]:
import numpy as np

grid = [i for i in jnp.arange(0.001, 0.101, 0.001)]
grid += [i for i in jnp.arange(0.11, 0.91, 0.01)]
grid += [i for i in jnp.arange(0.901, 1, 0.001)]

In [61]:

grid = np.array(grid)
surface = np.zeros(len(grid))

In [62]:

surface[:-1] = np.sum(
    np.array([[(grid[i] - grid[i - 1]) * (grid[j] - grid[j - 1]) for i in range(1, len(grid))] for j in
               range(1, len(grid))]), axis=1)
surface[-1] = surface[-2]

In [63]:
len(grid)

279

In [65]:
grid

array([0.001     , 0.002     , 0.003     , 0.004     , 0.005     ,
       0.006     , 0.007     , 0.008     , 0.009     , 0.01      ,
       0.011     , 0.012     , 0.013     , 0.014     , 0.015     ,
       0.016     , 0.017     , 0.018     , 0.019     , 0.02      ,
       0.021     , 0.022     , 0.023     , 0.024     , 0.025     ,
       0.026     , 0.027     , 0.028     , 0.029     , 0.03      ,
       0.031     , 0.032     , 0.033     , 0.034     , 0.035     ,
       0.036     , 0.037     , 0.038     , 0.039     , 0.04      ,
       0.041     , 0.042     , 0.043     , 0.044     , 0.045     ,
       0.046     , 0.047     , 0.048     , 0.049     , 0.05      ,
       0.051     , 0.052     , 0.053     , 0.054     , 0.055     ,
       0.056     , 0.057     , 0.058     , 0.059     , 0.06      ,
       0.061     , 0.062     , 0.063     , 0.064     , 0.06500001,
       0.06600001, 0.067     , 0.068     , 0.06900001, 0.07000001,
       0.071     , 0.072     , 0.07300001, 0.07400001, 0.075  