In [9]:
import matplotlib.pyplot as plt
import numpy as np
import pickle


s_list = [5]
Ry_list = [0.25]
no_datasets = 1

In [10]:
result = dict()
for i in range(no_datasets):
    for (s, Ry) in zip(s_list, Ry_list):
        with open(f'out_{i}_{s}_{Ry}.pickle', 'rb') as handle:
            result[i, s, Ry] = pickle.load(handle)

In [6]:
for i in range(no_datasets):
    for (s, Ry) in zip(s_list, Ry_list):
        R2_vs, q_vs, z_vs, sigma2_vs, beta_v_tilde = result[i, s, Ry]

        plt.hist(R2_vs)
        plt.title(f"R2_hist_{i}_{s}_{Ry}.png")
        plt.savefig(f'R2_hist_{i}_{s}_{Ry}.png')
        plt.close()

        plt.hist(q_vs)
        plt.title(f"q_hist_{i}_{s}_{Ry}.png")
        plt.savefig(f'q_hist_{i}_{s}_{Ry}.png')
        plt.close()


        plt.hist(sigma2_vs)
        plt.title(f"sigma2_hist_{i}_{s}_{Ry}.png")
        plt.savefig(f'sigma2_hist_{i}_{s}_{Ry}.png')
        plt.close()

In [39]:
import jax.numpy as jnp
import jax
z = [0, 1, 0]
X = [[2, 3, 4], [5, 6, 7], [8, 9, 10]]
X = jnp.array(X)
z = jnp.array(z)
print(reconstruct(X, z))

[[3. 0. 0.]
 [6. 0. 0.]
 [9. 0. 0.]]


In [41]:
reconstruct(X, z).T@reconstruct(X, z)

Array([[126.,   0.,   0.],
       [  0.,   0.,   0.],
       [  0.,   0.,   0.]], dtype=float32)

In [81]:
jnp.where(z == 1, X, z)

Array([[0, 3, 0],
       [0, 6, 0],
       [0, 9, 0]], dtype=int32)

In [82]:
z

Array([0, 1, 0], dtype=int32)

In [60]:
import numpy as np

grid = [i for i in jnp.arange(0.001, 0.101, 0.001)]
grid += [i for i in jnp.arange(0.11, 0.91, 0.01)]
grid += [i for i in jnp.arange(0.901, 1, 0.001)]

In [61]:

grid = np.array(grid)
surface = np.zeros(len(grid))

In [62]:

surface[:-1] = np.sum(
    np.array([[(grid[i] - grid[i - 1]) * (grid[j] - grid[j - 1]) for i in range(1, len(grid))] for j in
               range(1, len(grid))]), axis=1)
surface[-1] = surface[-2]

In [63]:
len(grid)

279

In [4]:
result

{(0,
  6,
  0.02): (Array([0.76999986, 0.82999986, 0.77999985, 0.7599999 , 0.7399999 ],      dtype=float32), Array([0.85999984, 0.8199999 , 0.902     , 0.7999999 , 0.905     ],      dtype=float32), Array([[ True,  True,  True,  True, False,  True,  True,  True, False,
           True,  True,  True,  True,  True,  True,  True,  True,  True,
          False,  True,  True,  True,  True, False, False,  True,  True,
          False,  True,  True,  True,  True,  True,  True,  True,  True,
           True,  True,  True,  True,  True, False, False,  True,  True,
           True,  True,  True,  True,  True,  True,  True,  True,  True,
          False, False,  True, False,  True,  True,  True,  True, False,
          False,  True,  True,  True,  True,  True,  True,  True,  True,
           True,  True,  True,  True,  True,  True,  True,  True,  True,
          False,  True,  True,  True,  True,  True,  True,  True,  True,
           True,  True,  True,  True,  True,  True,  True,  True,  True,
 

In [11]:
result

{(0,
  5,
  0.25): (Array([0.36999995, 0.001     , 0.001     , 0.10000001, 0.001     ,
         0.14999999, 0.001     , 0.9729991 , 0.002     , 0.09200001,
         0.001     , 0.6599999 , 0.001     , 0.4699999 , 0.001     ,
         0.6899999 , 0.001     , 0.7399999 , 0.001     , 0.88999987,
         0.001     , 0.001     , 0.11      , 0.001     , 0.45999992,
         0.001     , 0.001     , 0.84999985, 0.001     , 0.001     ,
         0.001     , 0.001     , 0.9579993 , 0.001     , 0.31999993,
         0.001     , 0.6399999 , 0.001     , 0.7099999 , 0.001     ,
         0.001     , 0.93799955, 0.001     , 0.20999998, 0.001     ,
         0.34999996, 0.001     , 0.33999997, 0.001     , 0.001     ,
         0.13999999, 0.001     , 0.18999998, 0.001     , 0.001     ,
         0.9939988 , 0.002     , 0.82999986, 0.001     , 0.067     ,
         0.001     , 0.08100001, 0.001     , 0.44999993, 0.001     ,
         0.6099999 , 0.001     , 0.21999997, 0.001     , 0.24999997,
         0.001  